version: '3.8'

services:
  adk:
    image: mcr.microsoft.com/devcontainers/python:3
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-atlas-local:8.0.3-20250506T093411Z
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
      - ../..:/workspaces:cached
    ports:
      - 27017:27017

volumes:
  mongodb-data: